### PR TITLE
Rewrite and new features

### PR DESCRIPTION
**Pull request by AmauryCarrade**
When I first contributed to this plugin, I was not as experienced as I am currently in Java. I looked at the code recently and... well, it was not in my standards of good code.

So I feel the motivation to improve it a “little bit”. I reorganized the plugin, helped by a library I contributed to ([zLib](https://github.com/zDevelopers/zLib)).

Separated classes, real GUI API to manage them, cleaner code, easier-to-use internal (and external) API, bug fixes, plus the new features:
 - live-updating GUIs;
 - the teleportation and arena GUIs are paginated, supporting an arbitrary number of spectators and arenas (thanks to the GUI API, implementing native paginated GUIs—see [the teleportation GUI](https://github.com/pgmann/SpectatorPlus/blob/rewrite/SpectatorPlus/src/com/pgcraft/spectatorplus/guis/TeleportationGUI.java) for an example);
 - little improvements on style;
 - probably more to come.

This is made to have a nicer code, but it will also greatly simplify the plugin's maintenance, making easier to add new features or to fix bugs.

~~The licence headers are sometimes incorrect (my name only and CeCILL instead of MPL), I'm aware of this; I'll fix that later.~~

*Don't merge now.*

### CODE REVIEW

**Comment by pgmann** [comment]
Wow! That's quite a PR you have there. Glad you've decided to do this :)
With the Android app I'm working on at the minute I'm quite busy but if I can help just let me know ;)

**Comment by AmauryCarrade** [comment]
I'm working on this with a clear idea of what I want so it's fine at the moment :) .

**Comment by pgmann** [comment]
If you're feeling up to it you could rename `com.pgcraft` to `cf.pgmann` in the package name, as that would make more sense due to the fact it's my actual website.

**Comment by AmauryCarrade** [comment]
Changing the package would break any plugin using the API, are you sure it's a good idea as I'm trying to minimise the breaks?

Currently the only broken thing is the arenas API, for a similar reason (moved to an `arenas` subpackage). The other parts of the API are unchanged (at least for an user point of view).

**Comment by pgmann** [comment]
jenkins build please.

**Comment by AmauryCarrade** [comment]
Nice

**Comment by pgmann** [comment]
Magic!

**Comment by AmauryCarrade** [comment]
(Why not a build on push?)

**Comment by pgmann** [comment]
It may build on push as well, we'll have to see. That would be ideal. (It's important not to build PR's from the general public, it basically grants them shell access to my jenkins server)

**Comment by pgmann** [comment]
Can this be built on Jenkins?

**Comment by pgmann** [comment]
ok to build.

**Comment by pgmann** [comment]
jenkins build please.

**Comment by pgmann** [comment]
Ah perfect, passed Jenkins build.

**Comment by pgmann** [comment]
It built automatically, as I suspected.

**Comment by AmauryCarrade** [comment]
Well, I think all the work is done, tests excepted (but it works well, in my local server).
The version should be changed to 3.0 I think, because this version completely breaks the compatibility of some part of the API and adds a lot of new features and polishments.

Also, should the whole `SpectateAPI` be deprecated? All SP-related actions can be executed through the internal features, like this, so is the dedicated API class really needed?
```java
SpectatorPlus.get().getPlayerData(player).setSpectating(true);

Arena arena = SpectatorPlus.get().getArenasManager().registerArena(new Arena(...));
SpectatorPlus.get().getPlayerData(player).setArena(arena);

// etc.
```

**Comment by AmauryCarrade** [comment]
> The version should be changed to 3.0 I think, because this version completely breaks the compatibility of some part of the API and adds a lot of new features and polishments.

Version updated to B3.0 until the stable release.

> Also, should the whole `SpectateAPI` be deprecated? All SP-related actions can be executed through the internal features, so is the dedicated API class really needed?

I changed my mind as it's an useful shortcut. Your opinion?

---

I think this PR can be merged.

**Comment by pgmann** [comment]
I think keep the API, and I'm happy to use version 3.0 as the next stable
version. I'm fine with a merge as everything seems fine.

(Sorry, forgot to reply to your last comment, read the email then forgot to
reply!)

**Comment by AmauryCarrade** [comment]
I had a few things to fix & improve. Waiting for the build; then I'll merge.

**Comment by pgmann** [comment]
Just by the way, you may have noticed [my JavaDoc](https://ci.pgmann.cf/job/SpectatorPlus/javadoc/?com/pgcraft/spectatorplus/SpectateAPI.html) doesn't display. Do you have any idea of a fix for this? (look at the javascript console for errors)

**Comment by AmauryCarrade** [comment]
How the JavaDoc is generated on your CI server?
I tried to generate it using `mvn javadoc:javadoc` and [it works well](http://raw.carrade.eu/s/1451925085.png).

On my Jenkins server, the [JavaDocs](http://jenkins.carrade.eu/job/zLib/javadoc) are generated using the JavaDoc plugin and these Maven goals.
```
clean install javadoc:javadoc
```

Maven goals

**Comment by pgmann** [comment]
Exactly the same as mine then, including goals. Could it be to do with
HTTPS?

**Comment by pgmann** [comment]
It may be useful to note I have an Apache reverse proxy between my Jenkins and the web (to get it on the same port as my webserver)

**Comment by AmauryCarrade** [comment]
Same for my server. A Content Security Policy blocking is weird on the same domain and the same protocol...

**Comment by AmauryCarrade** [comment]
You may want to [try this](https://wiki.jenkins-ci.org/display/JENKINS/Configuring+Content+Security+Policy#ConfiguringContentSecurityPolicy-JavadocPlugin).

**Comment by pgmann** [comment]
Not sure how to set the CSP header in the /etc/init.d/jenkins script, can't see where the $JENKINS_ARGS variable is set...

**Comment by AmauryCarrade** [comment]
No idea, sorry...

**Comment by pgmann** [comment]
Would you please check if this now works for you? It works in my browser after clearing the cache (I'm assuming the extra-strict CSP header was cached)

**Comment by AmauryCarrade** [comment]
It works on my side :) .

**Comment by pgmann** [comment]
Great, glad the problem's solved then :)

**Pull request merged**
